/*
 * Script 05: Cortex Search Service for POD Documents
 * Creates: POD_SEARCH_CORPUS (denormalized), POD_SEARCH_SERVICE
 * Note: Cortex Search requires VARCHAR columns - BOOLEAN/DATE are cast
 */

-- Denormalized search corpus joining PODs + customers + carriers
CREATE OR REPLACE TABLE AI_PLATFORM_DEV.SEMANTIC.POD_SEARCH_CORPUS AS
SELECT
    p.POD_ID,
    p.SHIPMENT_ID,
    p.ORDER_ID,
    c.CUSTOMER_NAME,
    c.CUSTOMER_SEGMENT,
    cr.CARRIER_NAME,
    cr.CARRIER_TYPE,
    p.DELIVERY_DATE,
    p.DELIVERY_CITY,
    p.DELIVERY_STATE,
    p.POD_STATUS,
    p.SIGNED_BY,
    p.EXCEPTION_FLAG,
    p.EXCEPTION_NOTES,
    p.DAMAGE_REPORTED,
    p.DAMAGE_DESCRIPTION,
    p.SIGNATURE_PRESENT,
    p.PARTIAL_DELIVERY,
    p.PACKAGES_RECEIVED,
    p.PACKAGES_EXPECTED,
    p.POD_TEXT_CONTENT,
    COALESCE(p.POD_TEXT_CONTENT, '') || CHR(10) || CHR(10) ||
    'Customer: ' || COALESCE(c.CUSTOMER_NAME, 'Unknown') || CHR(10) ||
    'Carrier: ' || COALESCE(cr.CARRIER_NAME, 'Unknown') || CHR(10) ||
    'Status: ' || COALESCE(p.POD_STATUS, 'Unknown') || CHR(10) ||
    'City: ' || COALESCE(p.DELIVERY_CITY, 'Unknown') || CHR(10) ||
    CASE WHEN p.EXCEPTION_FLAG
         THEN 'EXCEPTION: ' || COALESCE(p.EXCEPTION_NOTES, 'No details') || CHR(10)
         ELSE '' END ||
    CASE WHEN p.DAMAGE_REPORTED
         THEN 'DAMAGE: ' || COALESCE(p.DAMAGE_DESCRIPTION, 'No details') || CHR(10)
         ELSE '' END ||
    CASE WHEN NOT p.SIGNATURE_PRESENT
         THEN 'WARNING: Missing signature' || CHR(10)
         ELSE '' END
    AS SEARCH_TEXT
FROM AI_PLATFORM_DEV.CURATED.POD_FACT p
LEFT JOIN AI_PLATFORM_DEV.CURATED.DIM_CUSTOMERS c ON p.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN AI_PLATFORM_DEV.CURATED.DIM_CARRIERS cr ON p.CARRIER_ID = cr.CARRIER_ID;

-- Cortex Search Service
CREATE OR REPLACE CORTEX SEARCH SERVICE AI_PLATFORM_DEV.SEMANTIC.POD_SEARCH_SERVICE
  ON SEARCH_TEXT
  ATTRIBUTES POD_ID, SHIPMENT_ID, ORDER_ID, CUSTOMER_NAME, CARRIER_NAME,
             DELIVERY_DATE, DELIVERY_CITY, POD_STATUS, EXCEPTION_FLAG,
             EXCEPTION_NOTES, DAMAGE_REPORTED, SIGNATURE_PRESENT
  WAREHOUSE = AI_WH
  TARGET_LAG = '1 hour'
  COMMENT = 'Semantic search over POD documents'
AS
  SELECT
    SEARCH_TEXT,
    POD_ID,
    SHIPMENT_ID,
    ORDER_ID,
    CUSTOMER_NAME,
    CARRIER_NAME,
    DELIVERY_DATE::VARCHAR AS DELIVERY_DATE,
    DELIVERY_CITY,
    POD_STATUS,
    EXCEPTION_FLAG::VARCHAR AS EXCEPTION_FLAG,
    EXCEPTION_NOTES,
    DAMAGE_REPORTED::VARCHAR AS DAMAGE_REPORTED,
    SIGNATURE_PRESENT::VARCHAR AS SIGNATURE_PRESENT
  FROM AI_PLATFORM_DEV.SEMANTIC.POD_SEARCH_CORPUS;
